import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:memuno_app/src/app/bootstrap/firebase/firebase_options_development.dart'
    as firebase_options_development;
import 'package:memuno_app/src/app/bootstrap/firebase/firebase_options_production.dart'
    as firebase_options_production;
import 'package:memuno_app/src/app/bootstrap/firebase/firebase_options_staging.dart'
    as firebase_options_staging;

/// The three long-living environments we support.
///
/// We treat these as "first-class" app modes:
/// - development: local/dev bundle id + dev backend project
/// - staging: pre-release/TestFlight/Play internal + staging backend project
/// - production: App Store / Play production + production backend project
///
/// Notes:
/// - Environments are mapped from Flutter flavors (see [appFlavor]).
/// - All environments can share the same codebase, but must not share secrets.
enum AppEnvironment {
  /// Local developer build (never uploaded).
  development,

  /// Pre-release build used for TestFlight / Play internal testing.
  staging,

  /// Public release build distributed via stores.
  production,
}

/// Environment secrets injected via `--dart-define`.
///
/// Why we keep them in a dedicated type:
/// - Centralize validation in debug builds (fail fast).
/// - Pass secrets through the app as a single, explicit object.
/// - Avoid scattering `String.fromEnvironment(...)` calls across the codebase.
///
/// Security note:
/// - Do not log secrets.
/// - Keep secrets out of source control.
/// - Use `--dart-define` or build-time injection in CI.
final class AppSecrets {
  /// Creates a secrets bundle for the current environment.
  const AppSecrets({
    required this.supabaseUrl,
    required this.supabasePublishableKey,
  });

  /// Supabase project URL (e.g. https://xxxx.supabase.co).
  final String supabaseUrl;

  /// Supabase public key for the project.
  ///
  /// Note: This is safe to ship in the app, but must match your RLS policies.
  final String supabasePublishableKey;

  /// Validates that required secrets are present.
  ///
  /// We intentionally only assert in debug/profile-like scenarios.
  /// In release builds, missing secrets should be prevented by CI/build setup.
  void assertValid() {
    assert(() {
      if (supabaseUrl.isEmpty) {
        throw FlutterError('Missing dart-define: SUPABASE_URL');
      }
      if (supabasePublishableKey.isEmpty) {
        throw FlutterError('Missing dart-define: SUPABASE_PUBLISHABLE_KEY');
      }
      return true;
    }());
  }
}

/// Fully resolved runtime configuration for the app.
///
/// This is the "single object" we can pass to bootstrappers/services that need to
/// know the environment or platform configuration.
///
/// We keep this immutable and fully precomputed.
final class AppConfig {
  /// Creates the complete app configuration.
  const AppConfig({
    required this.environment,
    required this.authCallbackRedirect,
    required this.secrets,
    required this.firebaseOptions,
  });

  /// The resolved environment derived from [appFlavor].
  final AppEnvironment environment;

  final String authCallbackRedirect;

  /// Secrets for the resolved environment.
  final AppSecrets secrets;

  /// Firebase options for the resolved environment and platform.
  final FirebaseOptions firebaseOptions;

  /// Convenience getters for readable environment checks.
  /// Returns true when running a development build.
  bool get isDevelopment => environment == AppEnvironment.development;

  /// Returns true when running a staging build.
  bool get isStaging => environment == AppEnvironment.staging;

  /// Returns true when running a production build.
  bool get isProduction => environment == AppEnvironment.production;
}

/// Resolves environment + secrets + firebase options.
///
/// Source of truth:
/// - [appFlavor] is generated by Flutter flavors (via `flavors.dart`).
/// - Secrets are injected via `--dart-define`.
/// - Firebase options are generated by flutterfire for each flavor.
///
/// Usage:
/// - Bootstrapping (Supabase / Firebase / Crashlytics)
/// - Feature flags and environment-based toggles
final class AppEnv {
  /// Private constructor because this is a pure static utility.
  const AppEnv._();

  /// Maps the generated [appFlavor] string to our [AppEnvironment] enum.
  ///
  /// Notes:
  /// - Flutter flavors can vary by build system; we keep mapping tolerant.
  /// - Any unknown value falls back to [AppEnvironment.development].
  static AppEnvironment get environment {
    return switch (appFlavor) {
      'production' => AppEnvironment.production,
      'staging' => AppEnvironment.staging,
      _ => AppEnvironment.development,
    };
  }

  /// Deep-link callback URI used for Supabase auth redirects in the
  /// active flavor.
  static String get authCallbackRedirect {
    return switch (environment) {
      AppEnvironment.production => 'dev.coderave.memunoapp://auth/callback',
      AppEnvironment.staging => 'dev.coderave.memunoapp.stg://auth/callback',
      AppEnvironment.development =>
        'dev.coderave.memunoapp.dev://auth/callback',
    };
  }

  /// Deep-link callback URIs supported across all flavors.
  static Set<String> get allAuthCallbackRedirects => const <String>{
    'dev.coderave.memunoapp://auth/callback',
    'dev.coderave.memunoapp.stg://auth/callback',
    'dev.coderave.memunoapp.dev://auth/callback',
  };

  /// Custom URL schemes accepted for deep links across all flavors.
  static Set<String> get supportedDeepLinkSchemes {
    return allAuthCallbackRedirects
        .map((String uri) => Uri.parse(uri).scheme)
        .toSet();
  }

  /// Convenience environment checks.
  static bool get isDevelopment => environment == AppEnvironment.development;
  static bool get isStaging => environment == AppEnvironment.staging;
  static bool get isProduction => environment == AppEnvironment.production;

  /// Lazily resolves secrets once per process.
  ///
  /// We do this as a `final` initializer to:
  /// - avoid repeated parsing
  /// - ensure consistent values during app lifetime
  ///
  /// This field is private to prevent accidental modification.
  static final AppSecrets _secrets = (() {
    // `String.fromEnvironment` is compile-time injected by Flutter tooling.
    const String supabaseUrl = String.fromEnvironment('SUPABASE_URL');
    const String supabasePublishableKey = String.fromEnvironment(
      'SUPABASE_PUBLISHABLE_KEY',
    );

    final AppSecrets result = AppSecrets(
      supabaseUrl: supabaseUrl,
      supabasePublishableKey: supabasePublishableKey,
    );

    // Fail fast for developers. In release, your CI/build should guarantee this.
    if (!kReleaseMode) {
      result.assertValid();
    }

    return result;
  })();

  /// Returns the resolved secrets.
  static AppSecrets get secrets => _secrets;

  /// Returns the correct Firebase options for the current environment and platform.
  ///
  /// These files are generated by flutterfire and typically differ per flavor.
  static FirebaseOptions get firebaseOptions {
    return switch (environment) {
      AppEnvironment.production =>
        firebase_options_production.DefaultFirebaseOptions.currentPlatform,
      AppEnvironment.staging =>
        firebase_options_staging.DefaultFirebaseOptions.currentPlatform,
      AppEnvironment.development =>
        firebase_options_development.DefaultFirebaseOptions.currentPlatform,
    };
  }

  /// Returns the fully resolved runtime configuration.
  static AppConfig get config {
    final AppEnvironment env = environment;
    return AppConfig(
      environment: env,
      authCallbackRedirect: authCallbackRedirect,
      secrets: secrets,
      firebaseOptions: firebaseOptions,
    );
  }
}
