import 'package:firebase_core/firebase_core.dart';
import 'package:memuno_app/src/core/config/app_env.dart';

/// Initializes Firebase for the active flavor.
///
/// The Firebase options are generated by `flutterfire configure` per flavor.
Future<void> bootstrapFirebase() async {
  await Firebase.initializeApp(options: AppEnv.firebaseOptions);
}
